# Generated by Django 4.1.7 on 2023-03-03 19:57

from django.db import migrations


def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Harsh Gupta", email="HWNAOY@email.com",
            document="2222222", phone="00000000").save()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
